### ISSUE TITLE
CANNOT LINK EXECUTABLE: cannot locate symbol "signal" referenced by "/system/xbin/dbclient"...

### ISSUE THREAD

**Issue by ivantao8** [ribbons/android-dropbear#1]
got this error.
dropbear-armv7a-linux-androideabi.zip
device: android 4.4.2  armeabi-v7a

**Comment by ribbons** [comment]
I think I understand the cause - the build script was targeting Android API level 21 (Android 5 and above).  I've dropped the API level to 16 (Android 4.1 and above) for the armv7a-linux-androideabi build in the integration branch - could you give the binaries in https://github.com/ribbons/android-dropbear/suites/1543359121/artifacts/27490322 a go and see if they fix the problem?

**Comment by ivantao8** [comment]
dbclient works fine, thx.

**Comment by ribbons** [comment]
Great, glad to hear it.  I've pushed that API level change to master so future releases should run on 4.1 and above.

**Comment by ivantao8** [comment]
that would be great.
