### ISSUE TITLE
dbclient always exit with error: No auth methods could be used

### ISSUE THREAD

**Issue by venssy** [ribbons/android-dropbear#34]
I connet my server by `DROPBEAR_PASSWORD=password dbclient username@192.168.0.105`, and catch result like this:
`dbclient: Connection to venssy@192.168.0.105:22 exited: No auth methods could be used.`
RUN ON Android11.

**Comment by venssy** [comment]
Thanks for your reply, I luckly found another source that can use `DROPBEAR_PASSWORD` to auth my server, the executable provided is good, but for my unfamiliarity on c, I mignt not go futher to compile by myself, maybe you can take a look, the git url is [https://gitlab.com/fengshaun/android-dropbear](android-dropbear).

**Comment by ribbons** [comment]
Yes, I'm aware of a few other projects which maintain modified derivatives of Dropbear with additional features.  For this project my aim is to provide up-to-date builds of the upstream project for Android and maintaining larger out-of-tree patches rather goes against that as it increases the effort required for each new release.
