### ISSUE TITLE
Shell returned for users by Android 11 and above is rejected by default

### ISSUE THREAD

**Issue by konkong** [ribbons/android-dropbear#59]
The version I use is DROPBEAR_ 2024.86

I compared #21 and it seems to be caused by the difference in `shell is /bin/sh`.
The previous value was `shell is /system/bin/sh`.

using Dropbear, I put it in my old tablet, and then access it from my computer

```
TRACE4 (21159) 4.124322: enter recv_msg_userauth_request
TRACE4 (21159) 4.124369: enter checkusername
TRACE4 (21159) 4.124484: shell is /bin/sh
TRACE4 (21159) 4.124630: test shell is '/system/bin/sh'
TRACE4 (21159) 4.124651: no matching shell
[21159] Dec 28 16:38:08 User 'root' has invalid shell, rejected
TRACE4 (21159) 4.124726: recv_msg_userauth_request: 'none' request
TRACE4 (21159) 4.124741: enter send_msg_userauth_failure
TRACE4 (21159) 4.124759: auth fail: methods 2, 'publickey'
TRACE4 (21159) 4.124837: leave send_msg_userauth_failure
TRACE4 (21159) 4.125102: empty queue dequeing
TRACE4 (21159) 4.126258: process_packet: packet type = 50,  len 345
TRACE4 (21159) 4.126325: enter recv_msg_userauth_request
TRACE4 (21159) 4.126352: enter checkusername
TRACE4 (21159) 4.126383: checkusername: returning cached failure
TRACE4 (21159) 4.126405: enter pubkeyauth
TRACE4 (21159) 4.126457: enter send_msg_userauth_failure
TRACE4 (21159) 4.126493: auth fail: methods 2, 'publickey'
TRACE4 (21159) 4.126563: leave send_msg_userauth_failure
TRACE4 (21159) 4.126594: leave pubkeyauth
TRACE4 (21159) 4.126832: empty queue dequeing
[21159] Dec 28 16:38:08 Exit before auth from <192.168.1.51:1947>: (user 'root', 0 fails): Error reading: Connection reset by peer

```

**Comment by konkong** [comment]
Sorry, I forgot to mention
I use Dropbear, I put it in my old tablet, and then access it from my computer

**Comment by ribbons** [comment]
Thanks for the trace output, that was very helpful.  Looks like [commit 777b34dcc3](https://android.googlesource.com/platform/bionic/+/777b34dcc3e1a13ddcff75ed533a740fd262a4a9) in bionic changed the returned shell path for users back from `/system/bin/sh` to `/bin/sh` and (if I understand their tag names correctly) seems that change was delivered as part of Android 11.

I've just pushed 6863de2434457af5a0fca99dd2a60a1568a366a7 to the integration branch which should in theory fix your issue by adding /bin/sh to the default list of valid shell paths - could you grab the appropriate binary from the relevant artefact in [the actions run](https://github.com/ribbons/android-dropbear/actions/runs/12527420531) and let me know if it fixes the issue for you?

**Comment by konkong** [comment]
Thank you so much for your help with this!
`shell` path problem was indeed solved on my Android-10 tablet.

But I was stumped by the failure of the `authorized_keys` path verification. I can't create the .ssh folder directly in the android root directory, so I've been stuck at this exception. I don't know if I missed something


TRACE4 (1962) 3.594320: enter recv_msg_userauth_request
TRACE4 (1962) 3.594362: enter checkusername
TRACE4 (1962) 3.594417: shell is /bin/sh
TRACE4 (1962) 3.594722: test shell is '/bin/sh'
TRACE4 (1962) 3.594762: matching shell
TRACE4 (1962) 3.594777: uid = 0
TRACE4 (1962) 3.594792: leave checkusername
TRACE4 (1962) 3.594828: enter pubkeyauth
TRACE4 (1962) 3.594858: enter checkpubkey
TRACE4 (1962) 3.594927: enter checkpubkeyperms
TRACE4 (1962) 3.594959: enter checkfileperm(/)
TRACE4 (1962) 3.594991: leave checkfileperm: success
TRACE4 (1962) 3.595025: enter checkfileperm(//.ssh)
TRACE4 (1962) 3.595048: leave checkfileperm: stat() != 0
TRACE4 (1962) 3.595076: leave checkpubkeyperms
TRACE4 (1962) 3.595102: bad authorized_keys permissions, or file doesn't exist
TRACE4 (1962) 3.595151: leave checkpubkey: ret=-1
TRACE4 (1962) 3.595180: enter send_msg_userauth_failure
TRACE4 (1962) 3.595200: auth fail: methods 2, 'publickey'
TRACE4 (1962) 3.595282: leave send_msg_userauth_failure
TRACE4 (1962) 3.595328: leave pubkeyauth
TRACE4 (1962) 3.595551: empty queue dequeing
[1962] Dec 30 14:22:14 Exit before auth from <192.168.1.51:13719>: (user 'root', 0 fails): Error reading: Connection reset by peer

**Comment by ribbons** [comment]
Great, thanks for confirming that change fixes the valid shells check.  If you can raise a separate issue for the authorized_keys location issue I'll have a bit of a poke around and see what the situation is.
